name: fsf_finance
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.4.0
  cloud_firestore: ^2.3.0
  firebase_auth: ^3.0.1
  firebase_database: ^8.1.0

  flutter:
    sdk: flutter




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

#  assets:
#    - images
